version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: asset-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: asset_management
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5435:5432"

  backend:
    build: ./Backend
    container_name: asset-backend
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      PGUSER: postgres
      PGPASSWORD: admin234
      PGDATABASE: asset_management
      PGHOST: postgres
      PGPORT: 5432

  employee-asset:
    build: ./Employee-Asset
    container_name: employee-asset-ui
    ports:
      - "8004:80"
    depends_on:
      - backend

  hr-asset:
    build: ./HR-Asset
    container_name: hr-asset-ui
    ports:
      - "8005:80"
    depends_on:
      - backend

volumes:
  postgres_data:

